### ISSUE TITLE
Update to installation instructions

### ISSUE THREAD

**Issue by egel** [dominik59/polish_intellij_dictionary#3]
Hi @dominik59, first of all, thank you for building this repPrefeository. I found it very useful and it helped me build my polish dictionary in WebStorm from IntelliJ. 

I've tried your solution and I think it's worth updating regarding the latest changes in the IntelliJ interface.

The steps that I made in my WebStorm 2019.03:

1. Download repo and extract `pl_Pl.dic`
2. Open WebStorm -> Preferences -> Editor -> Spelling -> +
3. Select `pl_Pl.dic`
4. Done (actually, for me there was no need for restart/cache invalidation)

I hope this will helpful for other Polish programmers 🙂 Cheers ✌️

**Comment by dominik59** [comment]
@egel 
Thank you very much for letting me now, i have updated README :) 
I am happy to see that it helps someone somehow.

**Comment by PatrykKuniczak** [comment]
Thanks a lot!

Pozdro :)
